### ISSUE TITLE
Photos uploaded sideways

### ISSUE THREAD

**Issue by benhalpern** [forem/ForemWebView-ios#16]
**Describe the bug**
When I select a photo to upload, it appears normal in the selection process, but always winds out turned 90% (top is left-facing)..
**To Reproduce**
1. Go to "write a post"
2. Click on "Upload cover image"

Wait to see it upload and note that it is sideways.

**Comment by fdoxyz** [comment]
I'm pretty sure the moment the iOS camera takes the picture there's an orientation check we can make to display images properly. If #17 goes ahead with a native bridge implementation we can handle this natively.

If that's not the case (no native bridge implementation) it may not be a problem, I think/hope we can still tap in either the JavaScript (see [this example gist](https://gist.github.com/vdavid/3f9b66b60f52204317a4cc0e77097913)) context or when the image is processed in the backend. The backend is not ideal because the large image would have to travel through the network though.

**Comment by benhalpern** [comment]
Yeah, I'd favor native bridge in general 👍
